services:
  - type: web
    name: emailthing
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install -g pnpm@9 && pnpm install && pnpm exec playwright install --with-deps chromium && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.cache/ms-playwright
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "0"
      - key: RENDER
        value: "true"
